export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUPA_FAILURE";

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const CART_ITEMS_REQUEST = 'CART_ITEMS_REQUEST';
export const CART_ITEMS_SUCCESS = 'CART_ITEMS_SUCCESS';
export const CART_ITEMS_FAILURE = 'CART_ITEMS_FAILURE';
