const constants = {
    API_URL: 'http://localhost:8080/api',
    TITLE: "E-commerce",
    PRODUCT: 'Product',
    ERROR_TITLE: "The content you are looking for is not available at the moment",
    CONTINUE: "Continue Shopping",
    LOGIN: "Login",
    REGISTER: "Register",
    SHOPPING: "Shopping",
    FORGOT_PASSWORD: "Forgot Password?",
    REGISTER_POLICY: "By clicking Register, you agree to use out Terms and that you have read our Data Use Policy, including our Cookie Use",
    ADD_CART: "Add to Cart",
    LOGOUT: "Logout",
    HELLO: "Hello",
    CART: "cart",
    PRICE: "price",
    MY_CART: "My Cart",
    YOU: "You have",
    ITEMS: "item in your cart",
    TOTAL: "Total :",
    $: "$",
    NOT_FOUND: "404",
  };
  
  export default constants;